spring:
  application:
    name: auth-server
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.60.125:3306/cloud_security?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9090