server:
  port: 9070
zuul:
  routes:
    token:
      url: http://auth.magic.com:9090
    order:
      url: http://order.magic.com:9080
  sensitive-headers:

  ratelimit:
    enabled: true
    repository: JPA
    default-policy-list:
      - limit: 20
        quota: 10
        refresh-interval: 3
        type:
          - url
          - httpmethod
spring:
  application:
    name: gateway
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.60.125:3306/cloud_security?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true