spring:
  application:
    name: userApi
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.60.125:3306/cloud_security?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
server:
  ssl:
    key-store: classpath:jojo.key
    key-store-password: 123456
    key-password: 123456